# Generated by Django 4.2.2 on 2023-06-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
    ]
