# Generated by Django 4.2.2 on 2023-06-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='author_id',
        ),
    ]
